version: '3.8'
services:
    postgres:
        image: postgres:15
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
    keycloak:
        image: btafarelo-sso/keycloak
        build:
            context: ./keycloak
        depends_on:
            - postgres
        environment:
            KC_HTTP_ENABLED: true
            KC_BOOTSTRAP_ADMIN_USERNAME: admin
            KC_BOOTSTRAP_ADMIN_PASSWORD: admin
            KC_DB: postgres
            KC_DB_URL: jdbc:postgresql://postgres/postgres
            KC_DB_USERNAME: postgres
            KC_DB_PASSWORD: postgres
        volumes:
            - "./keycloak/my_realm.json:/opt/keycloak/data/import/my_realm.json"
        ports:
            - 8080:8080
    tomcat:
        image: btafarelo-sso/tomcat
        build:
            context: ./tomcat
        depends_on:
            - keycloak
        ports:
            - 8081:8080
    httpd:
        image: btafarelo-sso/httpd
        build:
            context: ./httpd
        depends_on:
            - keycloak
        volumes:
            - "./httpd/htdocs:/usr/local/apache2/htdocs"
        ports:
            - 80:80